apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: qtile-runners-vpa
  namespace: qtile-runners
spec:
  targetRef:
    apiVersion: "actions.github.com/v1alpha1"
    kind: AutoscalingRunnerSet
    name: "qtile"
  resourcePolicy:
    containerPolicies:
      - containerName: 'runner'
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 4
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Off"
