apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: ${RUNNER_INSTALLATION_NAME}-runners-vpa
  namespace: ${RUNNER_NAMESPACE}
spec:
  # Target the Shadow Deployment which has the same selector as the runners
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: ${RUNNER_INSTALLATION_NAME}-vpa-shadow
  resourcePolicy:
    containerPolicies:
      - containerName: 'runner'
        minAllowed:
          cpu: 100m
          memory: 256Mi
        maxAllowed:
          cpu: 4
          memory: 8Gi
        controlledResources: ["cpu", "memory"]
  updatePolicy:
    updateMode: "Off"
